[workspace]
resolver = "3"
members = ["eol_comments", "nesting_too_deep", "uninlined_format_args"]

[workspace.dependencies]
dylint_linting = "4.1.0"
dylint_uitesting = { version = "4.1.0", path = "/Users/tom/apps/dylint_uitesting" }
